version: '3.8'
services:
  db:
    image: postgis/postgis:15-3.3
    container_name: firsat_db
    environment:
      POSTGRES_USER: niko
      POSTGRES_PASSWORD: sifre123
      POSTGRES_DB: firsat_app
    ports:
      - "5432:5432"